/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FAQItem {
  'id' : bigint,
  'question' : string,
  'order' : bigint,
  'answer' : string,
}
export interface Product {
  'originalPrice' : bigint,
  'name' : string,
  'buy3Price' : [] | [bigint],
  'sizes' : Array<string>,
  'stockCount' : bigint,
  'benefits' : Array<string>,
  'salePrice' : bigint,
  'buy2Price' : [] | [bigint],
}
export interface Review {
  'id' : bigint,
  'verified' : boolean,
  'city' : string,
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export interface StoreSettings {
  'announcementText' : string,
  'countdownDurationHours' : bigint,
  'heroSubheadline' : string,
  'heroHeadline' : string,
}
export interface _SERVICE {
  'addFAQ' : ActorMethod<[FAQItem], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'getAllFAQs' : ActorMethod<[], Array<FAQItem>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getOrderCount' : ActorMethod<[], bigint>,
  'getProduct' : ActorMethod<[string], Product>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'incrementOrderCount' : ActorMethod<[], bigint>,
  'init' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'removeFAQ' : ActorMethod<[bigint], undefined>,
  'removeProduct' : ActorMethod<[string], undefined>,
  'removeReview' : ActorMethod<[bigint], undefined>,
  'transferAdmin' : ActorMethod<[Principal], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateStoreSettings' : ActorMethod<[StoreSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];