/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FAQItem = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Product = IDL.Record({
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'buy3Price' : IDL.Opt(IDL.Nat),
  'sizes' : IDL.Vec(IDL.Text),
  'stockCount' : IDL.Nat,
  'benefits' : IDL.Vec(IDL.Text),
  'salePrice' : IDL.Nat,
  'buy2Price' : IDL.Opt(IDL.Nat),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const StoreSettings = IDL.Record({
  'announcementText' : IDL.Text,
  'countdownDurationHours' : IDL.Nat,
  'heroSubheadline' : IDL.Text,
  'heroHeadline' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFAQ' : IDL.Func([FAQItem], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
  'incrementOrderCount' : IDL.Func([], [IDL.Nat], []),
  'init' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFAQ' : IDL.Func([IDL.Nat], [], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'removeReview' : IDL.Func([IDL.Nat], [], []),
  'transferAdmin' : IDL.Func([IDL.Principal], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FAQItem = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Product = IDL.Record({
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'buy3Price' : IDL.Opt(IDL.Nat),
    'sizes' : IDL.Vec(IDL.Text),
    'stockCount' : IDL.Nat,
    'benefits' : IDL.Vec(IDL.Text),
    'salePrice' : IDL.Nat,
    'buy2Price' : IDL.Opt(IDL.Nat),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const StoreSettings = IDL.Record({
    'announcementText' : IDL.Text,
    'countdownDurationHours' : IDL.Nat,
    'heroSubheadline' : IDL.Text,
    'heroHeadline' : IDL.Text,
  });
  
  return IDL.Service({
    'addFAQ' : IDL.Func([FAQItem], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
    'incrementOrderCount' : IDL.Func([], [IDL.Nat], []),
    'init' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFAQ' : IDL.Func([IDL.Nat], [], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'removeReview' : IDL.Func([IDL.Nat], [], []),
    'transferAdmin' : IDL.Func([IDL.Principal], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };