/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StoreSettings {
    announcementText: string;
    countdownDurationHours: bigint;
    heroSubheadline: string;
    heroHeadline: string;
}
export interface FAQItem {
    id: bigint;
    question: string;
    order: bigint;
    answer: string;
}
export interface Review {
    id: bigint;
    verified: boolean;
    city: string;
    name: string;
    reviewText: string;
    rating: bigint;
}
export interface Product {
    originalPrice: bigint;
    name: string;
    buy3Price?: bigint;
    sizes: Array<string>;
    stockCount: bigint;
    benefits: Array<string>;
    salePrice: bigint;
    buy2Price?: bigint;
}
export interface backendInterface {
    addFAQ(faq: FAQItem): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addReview(review: Review): Promise<void>;
    getAllFAQs(): Promise<Array<FAQItem>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllReviews(): Promise<Array<Review>>;
    getOrderCount(): Promise<bigint>;
    getProduct(name: string): Promise<Product>;
    getStoreSettings(): Promise<StoreSettings>;
    incrementOrderCount(): Promise<bigint>;
    init(): Promise<void>;
    isAdmin(): Promise<boolean>;
    removeFAQ(faqId: bigint): Promise<void>;
    removeProduct(productName: string): Promise<void>;
    removeReview(reviewId: bigint): Promise<void>;
    transferAdmin(newAdmin: Principal): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateStoreSettings(newSettings: StoreSettings): Promise<void>;
}
import type { Product as _Product } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFAQ(arg0: FAQItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async getAllFAQs(): Promise<Array<FAQItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFAQs();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return result;
        }
    }
    async getOrderCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderCount();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreSettings(): Promise<StoreSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreSettings();
            return result;
        }
    }
    async incrementOrderCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementOrderCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementOrderCount();
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async removeFAQ(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFAQ(arg0);
            return result;
        }
    }
    async removeProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProduct(arg0);
            return result;
        }
    }
    async removeReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReview(arg0);
            return result;
        }
    }
    async transferAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferAdmin(arg0);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStoreSettings(arg0: StoreSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreSettings(arg0);
            return result;
        }
    }
}
function from_candid_Product_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalPrice: bigint;
    name: string;
    buy3Price: [] | [bigint];
    sizes: Array<string>;
    stockCount: bigint;
    benefits: Array<string>;
    salePrice: bigint;
    buy2Price: [] | [bigint];
}): {
    originalPrice: bigint;
    name: string;
    buy3Price?: bigint;
    sizes: Array<string>;
    stockCount: bigint;
    benefits: Array<string>;
    salePrice: bigint;
    buy2Price?: bigint;
} {
    return {
        originalPrice: value.originalPrice,
        name: value.name,
        buy3Price: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.buy3Price)),
        sizes: value.sizes,
        stockCount: value.stockCount,
        benefits: value.benefits,
        salePrice: value.salePrice,
        buy2Price: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.buy2Price))
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Product_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalPrice: bigint;
    name: string;
    buy3Price?: bigint;
    sizes: Array<string>;
    stockCount: bigint;
    benefits: Array<string>;
    salePrice: bigint;
    buy2Price?: bigint;
}): {
    originalPrice: bigint;
    name: string;
    buy3Price: [] | [bigint];
    sizes: Array<string>;
    stockCount: bigint;
    benefits: Array<string>;
    salePrice: bigint;
    buy2Price: [] | [bigint];
} {
    return {
        originalPrice: value.originalPrice,
        name: value.name,
        buy3Price: value.buy3Price ? candid_some(value.buy3Price) : candid_none(),
        sizes: value.sizes,
        stockCount: value.stockCount,
        benefits: value.benefits,
        salePrice: value.salePrice,
        buy2Price: value.buy2Price ? candid_some(value.buy2Price) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
